"""add custom_foods table

Revision ID: 016f212d15e7
Revises: f674aa001f69
Create Date: 2026-04-09 22:02:24.597194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016f212d15e7'
down_revision: Union[str, None] = 'f674aa001f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('time_slots', sa.Column('start_date1', sa.Date(), nullable=False), schema='abc')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slots', 'start_date1', schema='abc')
    # ### end Alembic commands ###
