"""add custom_foods table

Revision ID: 14fa12c84532
Revises: 923193aa35a2
Create Date: 2026-04-09 21:39:11.415899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fa12c84532'
down_revision: Union[str, None] = '923193aa35a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('time_slots', sa.Column('start_date', sa.Date(), nullable=False), schema='abc')
    # op.add_column('time_slots', sa.Column('end_date', sa.Date(), nullable=True), schema='abc')
    # op.add_column('time_slots', sa.Column('service_name', sa.String(length=150), nullable=False), schema='abc')
    # op.drop_column('time_slots', 'date', schema='abc')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False), schema='abc')
    op.drop_column('time_slots', 'service_name', schema='abc')
    op.drop_column('time_slots', 'end_date', schema='abc')
    op.drop_column('time_slots', 'start_date', schema='abc')
    # ### end Alembic commands ###
