"""add column

Revision ID: 2c9b8ba3af12
Revises: e949659ec922
Create Date: 2026-03-29 17:23:37.023393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9b8ba3af12'
down_revision: Union[str, None] = 'e949659ec922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('latitude', sa.Float(), nullable=True), schema='abc')
    op.add_column('shops', sa.Column('longitude', sa.Float(), nullable=True), schema='abc')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True), schema='abc')
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True), schema='abc')
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True), schema='abc')
    op.create_unique_constraint(None, 'users', ['email'], schema='abc')
    op.drop_column('users', 'name', schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='abc')
    op.drop_constraint(None, 'users', schema='abc', type_='unique')
    op.drop_column('users', 'longitude', schema='abc')
    op.drop_column('users', 'latitude', schema='abc')
    op.drop_column('users', 'email', schema='abc')
    op.drop_column('shops', 'longitude', schema='abc')
    op.drop_column('shops', 'latitude', schema='abc')
    # ### end Alembic commands ###
