"""add open_time close_time to shops

Revision ID: 30e155aae98a
Revises: 38a2458117ef
Create Date: 2026-04-06 22:36:59.722659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e155aae98a'
down_revision: Union[str, None] = '38a2458117ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('open_time', sa.String(length=8), nullable=True), schema='abc')
    op.add_column('shops', sa.Column('close_time', sa.String(length=8), nullable=True), schema='abc')
    op.drop_constraint('shops_owner_id_fkey', 'shops', schema='abc', type_='foreignkey')
    op.create_foreign_key(None, 'shops', 'users', ['owner_id'], ['id'], source_schema='abc', referent_schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', schema='abc', type_='foreignkey')
    op.create_foreign_key('shops_owner_id_fkey', 'shops', 'users', ['owner_id'], ['id'], source_schema='abc', referent_schema='abc', ondelete='CASCADE')
    op.drop_column('shops', 'close_time', schema='abc')
    op.drop_column('shops', 'open_time', schema='abc')
    # ### end Alembic commands ###
