"""fix lat lng on shops not users

Revision ID: 38a2458117ef
Revises: 2c9b8ba3af12
Create Date: 2026-03-29 19:20:19.065661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a2458117ef'
down_revision: Union[str, None] = '2c9b8ba3af12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
