"""add custom_foods table

Revision ID: 923193aa35a2
Revises: ce8556bcfdfd
Create Date: 2026-04-08 18:48:47.005520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923193aa35a2'
down_revision: Union[str, None] = 'ce8556bcfdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('service_name', sa.String(length=150), nullable=True), schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'service_name', schema='abc')
    # ### end Alembic commands ###
