"""add custom_foods table

Revision ID: a978348b1007
Revises: dab32b4c0c8e
Create Date: 2026-04-25 11:59:36.343716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a978348b1007'
down_revision: Union[str, None] = 'dab32b4c0c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('date', sa.Date(), nullable=True), schema='abc')
    op.alter_column('time_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='abc')
    op.drop_column('time_slots', 'date', schema='abc')
    # ### end Alembic commands ###
