"""add custom_foods table

Revision ID: a99b23dbb74a
Revises: 9426eb81c1cd
Create Date: 2026-04-09 21:56:52.010864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99b23dbb74a'
down_revision: Union[str, None] = '9426eb81c1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('time_slots', sa.Column('start_date', sa.Date(), nullable=False), schema='abc')
    # op.drop_column('time_slots', 'date', schema='abc')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False), schema='abc')
    op.drop_column('time_slots', 'start_date', schema='abc')
    # ### end Alembic commands ###
