"""add custom_foods table

Revision ID: ce8556bcfdfd
Revises: 30e155aae98a
Create Date: 2026-04-08 17:52:37.177199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8556bcfdfd'
down_revision: Union[str, None] = '30e155aae98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('shop_id', sa.UUID(), nullable=True), schema='abc')
    op.create_foreign_key(None, 'bookings', 'shops', ['shop_id'], ['id'], source_schema='abc', referent_schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', schema='abc', type_='foreignkey')
    op.drop_column('bookings', 'shop_id', schema='abc')
    # ### end Alembic commands ###
