"""fix lat lng on shops not users

Revision ID: d3983e4ba15d
Revises: 42f6f51e351a
Create Date: 2026-03-29 11:25:29.997318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3983e4ba15d'
down_revision: Union[str, None] = '42f6f51e351a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_store_email', table_name='otp_store')
    op.drop_index('ix_otp_store_id', table_name='otp_store')
    op.drop_table('otp_store')
    op.drop_column('services', 'image_url', schema='abc')
    op.drop_index('ix_abc_users_email', table_name='users', schema='abc')
    op.drop_column('users', 'name', schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='abc')
    op.create_index('ix_abc_users_email', 'users', ['email'], unique=True, schema='abc')
    op.add_column('services', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True), schema='abc')
    op.create_table('otp_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='otp_store_pkey')
    )
    op.create_index('ix_otp_store_id', 'otp_store', ['id'], unique=False)
    op.create_index('ix_otp_store_email', 'otp_store', ['email'], unique=False)
    # ### end Alembic commands ###
