"""add custom_foods table

Revision ID: dab32b4c0c8e
Revises: 016f212d15e7
Create Date: 2026-04-25 11:55:52.397934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dab32b4c0c8e'
down_revision: Union[str, None] = '016f212d15e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('time_slots', sa.Column('date', sa.Date(), nullable=False), schema='abc')
    # op.alter_column('time_slots', 'start_time',
    #            existing_type=postgresql.TIME(),
    #            nullable=False,
    #            schema='abc')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='abc')
    op.drop_column('time_slots', 'date', schema='abc')
    # ### end Alembic commands ###
