"""fix lat lng on shops not users

Revision ID: e949659ec922
Revises: d3983e4ba15d
Create Date: 2026-03-29 11:26:03.448736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e949659ec922'
down_revision: Union[str, None] = 'd3983e4ba15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image_url', sa.String(length=500), nullable=True), schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'image_url', schema='abc')
    # ### end Alembic commands ###
