"""add custom_foods table

Revision ID: f674aa001f69
Revises: a99b23dbb74a
Create Date: 2026-04-09 21:58:06.849259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f674aa001f69'
down_revision: Union[str, None] = 'a99b23dbb74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('time_slots', sa.Column('start_date', sa.Date(), nullable=False), schema='abc')
    op.alter_column('time_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='abc')
    # op.drop_column('time_slots', 'date', schema='abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False), schema='abc')
    op.alter_column('time_slots', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='abc')
    op.drop_column('time_slots', 'start_date', schema='abc')
    # ### end Alembic commands ###
